services:
  - type: web
    name: zaui-coffee-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        value: your-db-host
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: zaui_coffee_db
      - key: DB_USER
        value: your-db-user
      - key: DB_PASSWORD
        value: your-db-password
      - key: JWT_SECRET
        value: your-jwt-secret
      - key: ZALO_OA_ID
        value: your-zalo-oa-id
      - key: ZALO_OA_SECRET
        value: your-zalo-oa-secret
      - key: CORS_ORIGIN
        value: https://your-frontend-domain.com
